diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
gpg.format=ssh
user.signingkey=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAcYRWRpqU+mn/BHQTFBfJxQ3Y8kVZ0ZYJF9CC4CgtEu
user.name=Anton Pham
user.email=anton@tekcent.com
commit.gpgsign=true
core.sshcommand=C:/Windows/System32/OpenSSH/ssh.exe
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github.com:atp0303/intervals-mcp-server.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.main.vscode-merge-base=origin/main
branch.dockerize.vscode-merge-base=origin/main
